type: object
properties:



  obsolete:
    type: string
  obsolete_since_date:
    type: string
  origin:
    type: string
  origin_en:
    type: string
    description: |
      This can be returned in many other languages
      like origin_fr (for french).
  origins:
    type: string
    description: |
      Origins of ingredients
  origins_hierarchy:
    type: array
    items:
      type: object
  origins_lc:
    type: string
  origins_tags:
    type: array
    items:
      type: object
  other_nutritional_substances_tags:
    type: array
    items:
      type: object

  packaging:
    type: string
  packaging_hierarchy:
    type: array
    items:
      type: string
  packaging_lc:
    type: string
  packaging_tags:
    type: array
    items:
      type: string
  packaging_text:
    type: string
    description: |
      Recycling instructions as raw text, e.g. Plastic
      bottle to recycle, Plastic cap to recycle.
      This will get automatically parsed and
      will be used to compute the Eco-Score.
      You can either request it (if it exists) or
      send it in a specific language.
    example: packaging_text_en
  packaging_text_en:
    type: string
    description: |
      This can be returned in many other languages
      like packaging_text_fr (for french).
  packagings:
    $ref: ./packagings/packagings.yaml
  packagings_complete:
    $ref: ./packagings/packagings_complete.yaml
  photographers_tags:
    type: array
    items:
      type: string
  pnns_groups_1:
    type: string
  pnns_groups_1_tags:
    type: array
    items:
      type: string
  pnns_groups_2:
    type: string
  pnns_groups_2_tags:
    type: array
    items:
      type: string
  popularity_key:
    type: integer
  popularity_tags:
    type: array
    items:
      type: string
  producer_version_id:
    type: string
  product_name:
    type: string
    description: |
      The name of the product
  product_name_en:
    type: string
    description: |
      The name of the product can also
      be in many other languages like
      product_name_fr (for french).
  product_quantity:
    type: string
  purchase_places:
    type: string
    description: |
      Country, state, or city where the product can be purchased.
    example: Paris
  purchase_places_tags:
    type: array
    items:
      type: string
  quantity:
    type: string
    description: |
      Quantity and Unit.
  removed_countries_tags:
    type: array
    items:
      type: object
  rev:
    type: integer
  scans_n:
    type: integer
  scores:
    type: object

  serving_quantity:
    type: string
    description: |
      Normalized version of serving_size.
      Note that this is NOT the number of servings by product.
      <small>(in perl, see `normalize_serving_size`)</small>
  serving_size:
    type: string
    description: |
      Serving size text (generally in g or ml).
      We expect a quantity + unit but the user is free to input any string.
  sortkey:
    type: integer
  sources:
    type: array
    items:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
        id:
          type: string
        images:
          type: array
          items:
            type: object
        import_t:
          type: integer
        manufacturer:
          type:
            - integer
            - string
        name:
          type: string
        source_licence:
          type: string
        source_licence_url:
          type: string
        url:
          type:
            - "null"
            - string
  sources_fields:
    type: object
    properties:
      org-gs1:
        type: object
        properties:
          gln:
            type: string
          gpcCategoryCode:
            type: string
          gpcCategoryName:
            type: string
          isAllergenRelevantDataProvided:
            type: string
          lastChangeDateTime:
            type: string
          partyName:
            type: string
          productionVariantDescription:
            type: string
          publicationDateTime:
            type: string
  states:
    type: string
  states_hierarchy:
    type: array
    items:
      type: string
  states_tags:
    type: array
    items:
      type: string
  stores:
    type: string
    description: |
      Distributor name.
    example: Walmart
  stores_tags:
    type: array
    items:
      type: string
  teams:
    type: string
  teams_tags:
    type: array
    items:
      type: string
  traces:
    type: string
    description: |
      List of substances that might cause allergies
      that are present in trace amounts in the product
      (this does not include the ingredients, as they
      are not only present in trace amounts).
      It is taxonomized with the allergens taxonomy.
  traces_from_ingredients:
    type: string
  traces_from_user:
    type: string
  traces_hierarchy:
    type: array
    items:
      type: object
  traces_lc:
    type: string
  traces_tags:
    type: array
    items:
      type: object
  unique_scans_n:
    type: integer
  unknown_ingredients_n:
    type: integer
  unknown_nutrients_tags:
    type: array
    items:
      type: object
  update_key:
    type: string
  vitamins_prev_tags:
    type: array
    items:
      type: object
  vitamins_tags:
    type: array
    items:
      type: object
