type: object
allOf:
  # temporary until I finish dispatching things
  - $ref: './product_todo.yaml'
  - $ref: './product_base.yaml'
  - $ref: './product_misc.yaml'
  - $ref: './product_tags.yaml'
  - $ref: './product_images.yaml'
  - $ref: './product_ecoscore.yaml'
  - $ref: './product_ingredients.yaml'
  - $ref: './product_nutrition.yaml'
  - $ref: './product_quality.yaml'
  - $ref: './product_extended.yaml'
  - $ref: './product_meta.yaml'
  - type: object
    properties:
      knowledge_panels:
        $ref: ./knowledge_panels/panels.yaml
