type: object
properties:
  image_front_small_url:
    type: string
  image_front_thumb_url:
    type: string
  image_front_url:
    type: string
  image_nutrition_small_url:
    type: string
  image_nutrition_thumb_url:
    type: string
  image_nutrition_url:
    type: string
  image_small_url:
    type: string
  image_thumb_url:
    type: string
  image_url:
    type: string
  images:
    description: |
      This contains properties for all images contained on the product
    type: object
    patternProperties:
      '(<?imgid>\d+)':
        type: object
        $ref: ./images/image.yaml
      '(<?image_type>front|nutrition|ingredients|packaging)_(?<language_code>\w\w)':
        type: object
        $ref: ./images/role_image.yaml

  last_image_dates_tags:
    type: array
    items:
      type: string
  last_image_t:
    type: integer

  selected_images:
    type: object
    patternProperties:
      '(<?image_type>front|packaging|ingredients|nutrition)':
        type: object
        description: URLs of thumbnails image of image of type `image_type`
        properties:
          display:
            description: |
              Thumbnail urls of product image (front) adapted to display on product page
            type: object
            $ref: 'images/image_urls.yaml'
          small:
            description: |
              Thumbnail urls of product image (front) adapted to display on product list page
            type: object
            $ref: 'images/image_urls.yaml'
          thumb:
            description: |
              Thumbnail urls of product image (front) in smallest format
            type: object
            $ref: 'images/image_urls.yaml'
